/**
 * Stable reason codes.
 *
 * PRD §40 Explainability: every denial and every state transition returns a stable
 * reason code plus the core evidence that produced it. These strings are part of the
 * external contract (MCP callers, CLI, audit records) and MUST NOT be renamed once
 * published — add a new code instead.
 */
export const ReasonCode = {
  // --- generic -------------------------------------------------------------
  OK: "OK",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INVALID_ARGUMENT: "INVALID_ARGUMENT",
  CONFLICT: "CONFLICT",
  /** A daemon-state path is missing, permissive, wrongly owned, or symlinked. */
  STATE_PATH_INSECURE: "STATE_PATH_INSECURE",

  // --- CP-HI-01 Managed Write Guard ---------------------------------------
  WRITE_REQUIRES_MANAGED_RUN: "WRITE_REQUIRES_MANAGED_RUN",
  WRITE_RUN_NOT_ACTIVE: "WRITE_RUN_NOT_ACTIVE",
  WRITE_BINDING_GENERATION_STALE: "WRITE_BINDING_GENERATION_STALE",
  WRITE_TARGET_OUTSIDE_RUN_SCOPE: "WRITE_TARGET_OUTSIDE_RUN_SCOPE",
  WRITE_PATH_NOT_CLAIMED: "WRITE_PATH_NOT_CLAIMED",
  WRITE_ALLOWED: "WRITE_ALLOWED",
  DIRECT_READ_ONLY_ALLOWED: "DIRECT_READ_ONLY_ALLOWED",
  DIRECT_MUTATION_DENIED: "DIRECT_MUTATION_DENIED",
  DIRECT_WRITE_ROOT_REQUIRED: "DIRECT_WRITE_ROOT_REQUIRED",
  WRITE_TARGET_RESOURCE_MISMATCH: "WRITE_TARGET_RESOURCE_MISMATCH",
  WRITE_EFFECT_FENCE_LOST: "WRITE_EFFECT_FENCE_LOST",
  // Source-read leases deny in three distinguishable ways: the caller holds no usable
  // lease (_REQUIRED), no lease can be taken because a managed write over the same source
  // is already authorised (_HELD), or a source mutation collided with a live lease
  // (_CONFLICT). A fourth spelling that nothing emitted was removed rather than kept as a
  // denial the runtime never returns.
  SOURCE_READ_LEASE_REQUIRED: "SOURCE_READ_LEASE_REQUIRED",
  SOURCE_READ_LEASE_HELD: "SOURCE_READ_LEASE_HELD",
  SOURCE_READ_LEASE_CONFLICT: "SOURCE_READ_LEASE_CONFLICT",

  // --- CP-HI-02 Single Runtime Authority ----------------------------------
  COMPLETION_AUTHORITY_DENIED: "COMPLETION_AUTHORITY_DENIED",
  GATE_AUTHORITY_DENIED: "GATE_AUTHORITY_DENIED",
  MERGE_AUTHORITY_DENIED: "MERGE_AUTHORITY_DENIED",
  RUN_STATE_TRANSITION_AUTHORITY_DENIED: "RUN_STATE_TRANSITION_AUTHORITY_DENIED",

  // --- CP-HI-03 Candidate Contract Pinning --------------------------------
  CONTRACT_DIGEST_MISMATCH: "CONTRACT_DIGEST_MISMATCH",
  CANDIDATE_CANNOT_WEAKEN_CONTRACT: "CANDIDATE_CANNOT_WEAKEN_CONTRACT",
  CONTRACT_CHANGE_REQUIRES_DEDICATED_RUN: "CONTRACT_CHANGE_REQUIRES_DEDICATED_RUN",
  REPOSITORY_IDENTITY_MISMATCH: "REPOSITORY_IDENTITY_MISMATCH",

  // --- CP-HI-04 Independent Quality Role ----------------------------------
  REVIEWER_NOT_INDEPENDENT: "REVIEWER_NOT_INDEPENDENT",
  REVIEWER_SESSION_IS_PRODUCER: "REVIEWER_SESSION_IS_PRODUCER",
  FINAL_CEO_SESSION_NOT_INDEPENDENT: "FINAL_CEO_SESSION_NOT_INDEPENDENT",

  // --- CP-HI-05 Trusted GitHub Credential ---------------------------------
  TRUSTED_CREDENTIAL_UNAVAILABLE: "TRUSTED_CREDENTIAL_UNAVAILABLE",
  TRUSTED_CREDENTIAL_LEAK_BLOCKED: "TRUSTED_CREDENTIAL_LEAK_BLOCKED",
  GATE_CREATOR_UNTRUSTED: "GATE_CREATOR_UNTRUSTED",
  GATE_PAYLOAD_PROVENANCE_INVALID: "GATE_PAYLOAD_PROVENANCE_INVALID",

  // --- CP-HI-06 Exact Evidence --------------------------------------------
  SNAPSHOT_STALE: "SNAPSHOT_STALE",
  SNAPSHOT_DIGEST_MISMATCH: "SNAPSHOT_DIGEST_MISMATCH",
  EVIDENCE_STALE: "EVIDENCE_STALE",
  HEAD_MOVED: "HEAD_MOVED",

  // --- CP-HI-07 Human Role ------------------------------------------------
  OWNER_AUTHORITY_NOT_DELEGABLE: "OWNER_AUTHORITY_NOT_DELEGABLE",
  HUMAN_GATE_REQUIRED: "HUMAN_GATE_REQUIRED",
  HUMAN_GATE_UNSATISFIED: "HUMAN_GATE_UNSATISFIED",

  // --- CP-HI-08 No Silent Degradation -------------------------------------
  EVIDENCE_MISSING: "EVIDENCE_MISSING",
  COVERAGE_INCOMPLETE: "COVERAGE_INCOMPLETE",
  PROBE_FAILED: "PROBE_FAILED",
  ISOLATION_LOST: "ISOLATION_LOST",
  VERIFICATION_GAP: "VERIFICATION_GAP",

  // --- run lifecycle -------------------------------------------------------
  RUN_TRANSITION_ILLEGAL: "RUN_TRANSITION_ILLEGAL",
  RUN_ALREADY_TERMINAL: "RUN_ALREADY_TERMINAL",
  RUN_OWNER_NOT_PINNED: "RUN_OWNER_NOT_PINNED",
  RUN_OWNER_REVOKED: "RUN_OWNER_REVOKED",
  RUN_DISPATCH_BLOCKED_CTO_DRAINING: "RUN_DISPATCH_BLOCKED_CTO_DRAINING",
  RUN_QUEUED_AWAITING_CTO: "RUN_QUEUED_AWAITING_CTO",
  RUN_CANCELLED: "RUN_CANCELLED",

  // --- task ----------------------------------------------------------------
  TASK_DEPENDENCY_UNSATISFIED: "TASK_DEPENDENCY_UNSATISFIED",
  TASK_DEPENDENCY_CYCLE: "TASK_DEPENDENCY_CYCLE",
  TASK_RECEIPT_MISSING: "TASK_RECEIPT_MISSING",
  TASK_RESULT_COUNT_MISMATCH: "TASK_RESULT_COUNT_MISMATCH",

  // --- session / binding ---------------------------------------------------
  SESSION_NOT_READY: "SESSION_NOT_READY",
  SESSION_INCARNATION_IMMUTABLE: "SESSION_INCARNATION_IMMUTABLE",
  BINDING_GENERATION_STALE: "BINDING_GENERATION_STALE",
  BINDING_REVOKED: "BINDING_REVOKED",
  BINDING_ALREADY_ACTIVE: "BINDING_ALREADY_ACTIVE",
  WORKER_BINDING_REQUIRED: "WORKER_BINDING_REQUIRED",
  PRIMARY_CTO_ALREADY_BOUND: "PRIMARY_CTO_ALREADY_BOUND",
  SWITCHOVER_BLOCKED_ACTIVE_RUNS: "SWITCHOVER_BLOCKED_ACTIVE_RUNS",
  REVOCATION_BLOCKED_ACTIVE_RUNS: "REVOCATION_BLOCKED_ACTIVE_RUNS",
  PRODUCER_HISTORY_UNAVAILABLE: "PRODUCER_HISTORY_UNAVAILABLE",
  SESSION_SECRET_STORAGE_UNAVAILABLE: "SESSION_SECRET_STORAGE_UNAVAILABLE",
  SESSION_SECRET_INVALID: "SESSION_SECRET_INVALID",
  SESSION_BUZZ_ACTOR_NOT_AUTHENTICATED: "SESSION_BUZZ_ACTOR_NOT_AUTHENTICATED",
  SESSION_BUZZ_ACTOR_ALREADY_BOUND: "SESSION_BUZZ_ACTOR_ALREADY_BOUND",
  SESSION_BUZZ_ACTOR_IMMUTABLE: "SESSION_BUZZ_ACTOR_IMMUTABLE",
  HANDOFF_ACK_REQUIRED: "HANDOFF_ACK_REQUIRED",
  HANDOFF_ACK_AUTHENTICATION_FAILED: "HANDOFF_ACK_AUTHENTICATION_FAILED",
  HANDOFF_PACKAGE_INCOMPLETE: "HANDOFF_PACKAGE_INCOMPLETE",
  RECOVERY_TAKEOVER_REQUIRES_UNREACHABLE_OWNER:
    "RECOVERY_TAKEOVER_REQUIRES_UNREACHABLE_OWNER",
  SESSION_STOP_FAILED: "SESSION_STOP_FAILED",

  // --- registries ----------------------------------------------------------
  MANIFEST_ACTIVATION_EVIDENCE_MISSING: "MANIFEST_ACTIVATION_EVIDENCE_MISSING",
  MANIFEST_ACTIVATION_GRANT_CONSUMED: "MANIFEST_ACTIVATION_GRANT_CONSUMED",
  REPOSITORY_CHECKOUT_ALREADY_REGISTERED: "REPOSITORY_CHECKOUT_ALREADY_REGISTERED",
  REPOSITORY_BINDING_CHANGE_REQUIRES_ACTIVATION:
    "REPOSITORY_BINDING_CHANGE_REQUIRES_ACTIVATION",
  TEMPORARY_REPOSITORY_SCOPE_VIOLATION: "TEMPORARY_REPOSITORY_SCOPE_VIOLATION",

  // --- resource claim ------------------------------------------------------
  CLAIM_WORKTREE_CONFLICT: "CLAIM_WORKTREE_CONFLICT",
  CLAIM_BRANCH_CONFLICT: "CLAIM_BRANCH_CONFLICT",
  CLAIM_PATH_CONFLICT: "CLAIM_PATH_CONFLICT",
  CLAIM_OWNER_GENERATION_REVOKED: "CLAIM_OWNER_GENERATION_REVOKED",
  CLAIM_EXPIRED: "CLAIM_EXPIRED",
  CLAIM_NOT_HELD: "CLAIM_NOT_HELD",
  SEMANTIC_CONFLICT_ADVISORY: "SEMANTIC_CONFLICT_ADVISORY",

  // --- verification --------------------------------------------------------
  VERIFICATION_COMMAND_FAILED: "VERIFICATION_COMMAND_FAILED",
  VERIFICATION_TIMEOUT: "VERIFICATION_TIMEOUT",
  VERIFICATION_INCOMPLETE: "VERIFICATION_INCOMPLETE",
  VERIFICATION_CI_HEAD_MISMATCH: "VERIFICATION_CI_HEAD_MISMATCH",
  VERIFICATION_CI_WORKFLOW_DIGEST_MISMATCH:
    "VERIFICATION_CI_WORKFLOW_DIGEST_MISMATCH",
  VERIFICATION_OUTPUT_TRUNCATED: "VERIFICATION_OUTPUT_TRUNCATED",
  SANDBOX_NETWORK_DENIED: "SANDBOX_NETWORK_DENIED",
  SANDBOX_SECRET_STRIPPED: "SANDBOX_SECRET_STRIPPED",
  SANDBOX_PATH_OUTSIDE_WORKTREE: "SANDBOX_PATH_OUTSIDE_WORKTREE",
  SANDBOX_CHILD_CLEANUP_FAILED: "SANDBOX_CHILD_CLEANUP_FAILED",
  SANDBOX_RESOURCE_LIMIT_UNAVAILABLE: "SANDBOX_RESOURCE_LIMIT_UNAVAILABLE",
  SANDBOX_RESOURCE_LIMIT_EXCEEDED: "SANDBOX_RESOURCE_LIMIT_EXCEEDED",
  VERIFICATION_REPOSITORY_UNTRUSTED: "VERIFICATION_REPOSITORY_UNTRUSTED",

  // --- blind review --------------------------------------------------------
  REVIEW_REQUIRED: "REVIEW_REQUIRED",
  REVIEW_PASS: "REVIEW_PASS",
  REVIEW_REVISE: "REVIEW_REVISE",
  REVIEW_BLOCK: "REVIEW_BLOCK",
  REVIEW_OMITTED_ITEMS_PRESENT: "REVIEW_OMITTED_ITEMS_PRESENT",
  REVIEW_INPUT_CONTAMINATED: "REVIEW_INPUT_CONTAMINATED",
  REVIEW_MANUAL_INVOCATION_DENIED: "REVIEW_MANUAL_INVOCATION_DENIED",

  // --- github kernel -------------------------------------------------------
  PR_BRANCH_CONTRACT_VIOLATION: "PR_BRANCH_CONTRACT_VIOLATION",
  PR_LINKAGE_MISSING: "PR_LINKAGE_MISSING",
  MERGE_GATE_MISSING: "MERGE_GATE_MISSING",
  MERGE_BASE_STALE: "MERGE_BASE_STALE",
  MERGE_HEAD_STALE: "MERGE_HEAD_STALE",
  MERGE_IDEMPOTENT_REPLAY: "MERGE_IDEMPOTENT_REPLAY",
  GITHUB_RECEIPT_PROTOCOL_VIOLATION: "GITHUB_RECEIPT_PROTOCOL_VIOLATION",
  MERGE_BRANCH_PROFILE_UNSATISFIED: "MERGE_BRANCH_PROFILE_UNSATISFIED",
  MERGE_CLAIM_INVALID: "MERGE_CLAIM_INVALID",
  MERGE_ORDER_VIOLATION: "MERGE_ORDER_VIOLATION",
  GATE_EVIDENCE_NOT_BACKED: "GATE_EVIDENCE_NOT_BACKED",
  POST_MERGE_CHECKS_NOT_DECLARED: "POST_MERGE_CHECKS_NOT_DECLARED",
  POST_MERGE_VERIFICATION_FAILED: "POST_MERGE_VERIFICATION_FAILED",
  DEPENDENT_MERGE_BLOCKED: "DEPENDENT_MERGE_BLOCKED",
  RELEASE_TAG_SEMVER_MISMATCH: "RELEASE_TAG_SEMVER_MISMATCH",
  RELEASE_TAG_COMMIT_NOT_ACCEPTED: "RELEASE_TAG_COMMIT_NOT_ACCEPTED",
  RELEASE_TAG_DUPLICATE: "RELEASE_TAG_DUPLICATE",
  ISSUE_PROJECTION_UNVERIFIED: "ISSUE_PROJECTION_UNVERIFIED",
  HOTFIX_PROPAGATION_INCOMPLETE: "HOTFIX_PROPAGATION_INCOMPLETE",

  // --- capacity ------------------------------------------------------------
  CAPACITY_PROBE_STALE: "CAPACITY_PROBE_STALE",
  CAPACITY_SENSOR_FILE_MISSING: "CAPACITY_SENSOR_FILE_MISSING",
  CAPACITY_SENSOR_FILE_STALE: "CAPACITY_SENSOR_FILE_STALE",
  CAPACITY_SENSOR_FILE_INVALID: "CAPACITY_SENSOR_FILE_INVALID",
  CAPACITY_ADMISSION_SUSPENDED: "CAPACITY_ADMISSION_SUSPENDED",
  CAPACITY_ADMISSION_CONSERVE: "CAPACITY_ADMISSION_CONSERVE",
  CAPACITY_BUCKET_EXHAUSTED: "CAPACITY_BUCKET_EXHAUSTED",
  CAPACITY_UNKNOWN_NOT_ROUTABLE: "CAPACITY_UNKNOWN_NOT_ROUTABLE",

  // --- continuity ----------------------------------------------------------
  COVERAGE_FULL: "COVERAGE_FULL",
  COVERAGE_PARTIAL: "COVERAGE_PARTIAL",
  COVERAGE_NONE: "COVERAGE_NONE",
  CONTINUITY_SURVIVAL_NO_COMPLETION: "CONTINUITY_SURVIVAL_NO_COMPLETION",
  RESTORE_WOULD_PREEMPT_INFLIGHT_OWNER: "RESTORE_WOULD_PREEMPT_INFLIGHT_OWNER",

  // --- ingress -------------------------------------------------------------
  INGRESS_ACTOR_NOT_ALLOWLISTED: "INGRESS_ACTOR_NOT_ALLOWLISTED",
  INGRESS_CHAT_NOT_ALLOWLISTED: "INGRESS_CHAT_NOT_ALLOWLISTED",
  INGRESS_SIGNATURE_INVALID: "INGRESS_SIGNATURE_INVALID",
  INGRESS_REPLAY_IGNORED: "INGRESS_REPLAY_IGNORED",
  INGRESS_NONCE_EXPIRED: "INGRESS_NONCE_EXPIRED",
  UNTRUSTED_CONTENT_IS_DATA: "UNTRUSTED_CONTENT_IS_DATA",
  MCP_PEER_UNAUTHENTICATED: "MCP_PEER_UNAUTHENTICATED",

  // --- outbox --------------------------------------------------------------
  OUTBOX_STALE_GENERATION_REJECTED: "OUTBOX_STALE_GENERATION_REJECTED",
  OUTBOX_RETARGETED: "OUTBOX_RETARGETED",
  OUTBOX_EXPIRED: "OUTBOX_EXPIRED",
  OUTBOX_DUPLICATE_SUPPRESSED: "OUTBOX_DUPLICATE_SUPPRESSED",
  OUTBOX_PAYLOAD_DIGEST_MISMATCH: "OUTBOX_PAYLOAD_DIGEST_MISMATCH",
  OUTBOX_TARGET_NOT_CURRENT: "OUTBOX_TARGET_NOT_CURRENT",
  OUTBOX_DELIVERY_REJECTED: "OUTBOX_DELIVERY_REJECTED",
  OUTBOX_RETRY_POLICY_UNAVAILABLE: "OUTBOX_RETRY_POLICY_UNAVAILABLE",

  // --- claim admission -----------------------------------------------------
  CLAIM_OWNER_NOT_RUN_OWNER: "CLAIM_OWNER_NOT_RUN_OWNER",

  // --- doctor / repair -----------------------------------------------------
  DOCTOR_HEALTHY: "DOCTOR_HEALTHY",
  DOCTOR_DEGRADED: "DOCTOR_DEGRADED",
  DOCTOR_BLOCKED: "DOCTOR_BLOCKED",
  DOCTOR_ERROR: "DOCTOR_ERROR",
  CANDIDATE_PIPELINE_ATTEMPT_STALE: "CANDIDATE_PIPELINE_ATTEMPT_STALE",
  REPAIR_NOT_ALLOWLISTED: "REPAIR_NOT_ALLOWLISTED",
  REPAIR_PRECONDITION_UNMET: "REPAIR_PRECONDITION_UNMET",
  REPAIR_REQUIRES_OWNER: "REPAIR_REQUIRES_OWNER",

  // --- bootstrap -----------------------------------------------------------
  BOOTSTRAP_FACTORY_RESULT_INSUFFICIENT: "BOOTSTRAP_FACTORY_RESULT_INSUFFICIENT",
  BOOTSTRAP_ACTIVATION_INCOMPLETE: "BOOTSTRAP_ACTIVATION_INCOMPLETE",
  BOOTSTRAP_MANIFEST_ABSOLUTE_PATH: "BOOTSTRAP_MANIFEST_ABSOLUTE_PATH",
  BOOTSTRAP_CTO_INELIGIBLE_FOR_PROMOTION: "BOOTSTRAP_CTO_INELIGIBLE_FOR_PROMOTION",
  BOOTSTRAP_CONTRACT_DRIFT: "BOOTSTRAP_CONTRACT_DRIFT",
  BOOTSTRAP_RESULT_OVERCLAIMS_ACTIVATION: "BOOTSTRAP_RESULT_OVERCLAIMS_ACTIVATION",
  RESOURCE_COLLISION: "RESOURCE_COLLISION",
  MANIFEST_NOT_PORTABLE: "MANIFEST_NOT_PORTABLE",

  // --- daemon --------------------------------------------------------------
  DAEMON_ALREADY_RUNNING: "DAEMON_ALREADY_RUNNING",
  DAEMON_LOCK_LOST: "DAEMON_LOCK_LOST",
  DAEMON_BACKOFF_ACTIVE: "DAEMON_BACKOFF_ACTIVE",
  DAEMON_STARTUP_FAILED: "DAEMON_STARTUP_FAILED",
  DAEMON_TIMER_FAILED: "DAEMON_TIMER_FAILED",
} as const;

export type ReasonCode = (typeof ReasonCode)[keyof typeof ReasonCode];

const ALL: ReadonlySet<string> = new Set(Object.values(ReasonCode));

export const isReasonCode = (value: string): value is ReasonCode => ALL.has(value);
